INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (1, 'Mai Phạm', 'johnpham@example.com', 'TWTfge15_5', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (2, 'Thành Hoàng', 'janehoang@example.com', '%%7YbMhumv', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (3, 'Kim Thị Mai', 'omai@example.com', '#jO2S%n896', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (4, 'Bà Lan Đặng', 'zmai@example.org', '@1zo1V0t37', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (5, 'Lâm Hoàng', 'johnpham@example.org', ')6*uPSYn)E', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (6, 'Anh Bùi', 'cduong@example.org', '%39_R6g!^b', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (7, 'Bà Yến Phạm', 'buijane@example.com', '#h61R2xS$7', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (8, 'Thành Vũ', 'john70@example.org', 'WL9APqFah$', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (9, 'Quý cô An Mai', 'janepham@example.net', 'p#(6WLNz%&', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (10, 'Phương Mai Đặng', 'jvu@example.net', '&fUoul&sd1', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (11, 'Hải Hoàng', 'nnguyen@example.com', '9MSZ6!kt$Z', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (12, 'Nhiên Vũ', 'hoangjane@example.org', '(+Wsro*Hf7', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (13, 'Bảo Xuân Hoàng', 'hoangjohn@example.org', '%5vf8XjQ3g', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (14, 'Chị Nhật Dương', 'janeduong@example.com', '$w7Eq&uUx%', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (15, 'Hạnh Thế Hoàng', 'tvu@example.com', 'QzBIB$6)+2', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (16, 'Hà Hoàng Vũ', 'johnmai@example.com', 'Tyng2_Xh%&', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (17, 'Cô Dương Vũ', 'jane35@example.net', 'pV(v7E#qtl', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (18, 'Hoàng Hữu Hoàng', 'tpham@example.org', 'z&L%30RyV4', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (19, 'Hồng Vũ', 'zvu@example.org', '@7AWo0m)KY', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (20, 'Duyên Vũ', 'janemai@example.org', 'M#1KmOlN*7', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (21, 'Hoàng Vũ', 'wpham@example.org', 'lM^Kbo)C(3', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (22, 'Ngọc Hoàng', 'janetran@example.org', '!lK5KTb%y4', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (23, 'Chị Hải Dương', 'johnmai@example.org', '18pkBL4v%V', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (24, 'Phúc Trần', 'john32@example.net', '3*s4Go*zMY', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (25, 'Minh Trí Mai', 'qnguyen@example.org', '$Md8SeKs9R', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (26, 'Nhật Thế Hoàng', 'vujane@example.net', '&7C2NhrM05', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (27, 'Phúc Đức Dương', 'jane85@example.org', '#yQU^Rja*4', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (28, 'Bà Lâm Lê', 'jane32@example.org', '(ngWqCm@g9', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (29, 'Quý ông Minh Dương', 'phamjane@example.com', '!21Rh^ZXxT', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (30, 'Huy Mai Bùi', 'vhoang@example.com', '$@iX_*QpX5', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (31, 'Hạnh Đặng', 'vujane@example.net', '*83v7W+y92', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (32, 'Hà Trần', 'phamjohn@example.org', 'S)Ykn0Yf0i', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (33, 'Hương Nguyễn', 'dangjohn@example.com', '+LI&4PFpTy', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (34, 'Trọng Thị Vũ', 'john14@example.com', '(2%3IjmoJ@', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (35, 'Quý ông Nhiên Vũ', 'duongjane@example.com', '&_iT6WUcJe', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (36, 'Anh Thế Dương', 'johnvu@example.net', 'B&7A!M)qwK', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (37, 'Chị An Mai', 'john08@example.org', 'G9O5POhe@P', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (38, 'Huy Trần', 'johndang@example.org', '(Bm%YMvfw8', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (39, 'Cô Hạnh Mai', 'gbui@example.com', '0rB1YZ3v&_', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (40, 'Quý cô An Trần', 'jane13@example.org', '@wD0yJvhmt', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (41, 'An Vũ', 'jane65@example.net', 'JIF9ViNh(7', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (42, 'Bà Vân Lê', 'janebui@example.org', '9LBY$mEQ+b', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (43, 'Chị Hải Vũ', 'cvu@example.com', 'U(69BiiC8C', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (44, 'Xuân Hoàng', 'jane41@example.org', '()7Sv0#h#L', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (45, 'Kim Mai Bảo Đặng', 'amai@example.net', 'b53XPHXz+!', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (46, 'Quý cô Nhật Nguyễn', 'johnnguyen@example.com', 'j3g5hUcm*j', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (47, 'Hà Phạm', 'nbui@example.org', 'R_QC55Mkif', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (48, 'Bà Chi Nguyễn', 'johnle@example.net', 'k_4T+E^wY&', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (49, 'Anh Anh Phạm', 'jane00@example.com', '%4GGd#0y#g', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (50, 'Nhật Văn Dương', 'maijohn@example.net', 'BTH!vREJ)7', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (51, 'Quang Dương', 'jane31@example.org', 'V_u8aXjtj+', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (52, 'Anh Hưng Phạm', 'lejane@example.org', '@Ky&6Jguw(', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (53, 'Vũ Đặng', 'nguyenjane@example.org', '*)K9UF4o5J', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (54, 'Bác Quang Phạm', 'john09@example.com', '*1#6%SonVQ', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (55, 'Hoàng Đặng', 'janenguyen@example.com', 'Y9l#2jCk!!', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (56, 'Hải Nguyễn', 'jane93@example.com', '&U5%iJYe%t', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (57, 'Chị Thảo Nguyễn', 'tranjane@example.com', 'zuv9PlPy6%', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (58, 'Chị Hương Đặng', 'jane56@example.net', 'ci6h#YJy%q', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (59, 'Hải Quang Vũ', 'janele@example.com', 'E_R5K2Hcij', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (60, 'Hà Xuân Đặng', 'gbui@example.net', '20*QmkUR@2', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (61, 'Hà Mai', 'johnnguyen@example.net', '#tzRCv3P#9', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (62, 'Chị Hà Nguyễn', 'jane76@example.com', 'IpL0N6Lkp@', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (63, 'Trung Trần', 'johnle@example.net', 'T4ld#8JttK', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (64, 'Anh Tú Lê', 'janemai@example.com', '(0Wl!SCoAq', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (65, 'Quang Phú Hoàng', 'duongjane@example.org', 'L(!7pLz$jr', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (66, 'Bà Xuân Bùi', 'jane71@example.net', 'g&t2_5GbfC', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (67, 'Hà Hoàng Dương', 'duongjohn@example.net', '17TBPUKB!w', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (68, 'Thảo Mai', 'bnguyen@example.com', '!&@^8UUvzu', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (69, 'Hưng Thế Nguyễn', 'jane24@example.org', ')AEGooDkD5', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (70, 'Bảo Nguyễn', 'yle@example.com', 'q%9nKcoy%$', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (71, 'Dũng Đặng', 'jane62@example.com', '@Rcc(0BhUy', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (72, 'Dũng Hoàng', 'john85@example.net', 'Mc6IDnrr)S', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (73, 'Phương Đức Đặng', 'lejane@example.org', '!JrBY8biC0', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (74, 'Hưng Vũ', 'dpham@example.org', '5&&5gOj9Vm', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (75, 'Thành Quang Mai', 'johnvu@example.net', 'o+^V9XJmt&', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (76, 'Ông Trung Lê', 'phamjane@example.org', 'x1rrAqXt%C', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (77, 'Bà Hương Hoàng', 'janepham@example.com', '%NQyFVgB)2', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (78, 'Hương Dương', 'xbui@example.org', '_8Lne9iR2Y', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (79, 'Chị Khoa Dương', 'john62@example.com', 'Y4!1fNDhD%', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (80, 'Khoa Lê', 'dvu@example.org', '_EynBxLp*3', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (81, 'Bà Hồng Đặng', 'jane12@example.org', 'i5qz(A4y)6', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (82, 'Tùng Dương', 'johntran@example.org', 'sfZqztIP#6', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (83, 'Thành Hữu Trần', 'janevu@example.net', 'Dl4T+fZz@!', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (84, 'Quý cô Duyên Phạm', 'dangjohn@example.org', '1EtH)Tgw!W', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (85, 'Kim Đức Dương', 'johnpham@example.net', 'ssNjuuG2%0', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (86, 'Bảo Thị Hoàng', 'janepham@example.net', 'o*2k8UjQ$N', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (87, 'Khoa Đặng', 'lejane@example.com', 'm9&!0OPjF8', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (88, 'Nhật Phạm', 'hoangjohn@example.net', 'a5zE)S3+&P', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (89, 'Bảo Xuân Trần', 'jane46@example.net', 'iCh+2LFfuv', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (90, 'Hạnh Mai', 'vujohn@example.com', '^bgTpOt12A', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (91, 'Thảo Mai', 'jane97@example.com', 'FK)9G1Wuf5', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (92, 'Khoa Tấn Vũ', 'maijane@example.org', 'je(0^U%p!b', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (93, 'Châu Mai', 'duongjohn@example.org', 'V$3jDsqa_N', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (94, 'Quý cô Lan Đặng', 'maijohn@example.org', '$_h5r7QmWv', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (95, 'Lâm Nguyễn', 'ohoang@example.org', '!@e7NEQg8P', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (96, 'Châu Bùi', 'jane84@example.org', 'b)&ru2YfjY', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (97, 'Phúc Xuân Lê', 'rnguyen@example.org', '5_VF9il**7', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (98, 'Cô Chi Trần', 'lejohn@example.org', 'Tn5^C!Dkb(', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (99, 'Bà Thành Đặng', 'buijohn@example.org', '#V82E)usR*', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (100, 'Bác Vũ Phạm', 'janehoang@example.org', '&H9Gz#pcIa', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (101, 'Kim Bảo Hoàng', 'lejane@example.org', 'zj9imWx_%J', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (102, 'Kim Trần', 'dangjohn@example.com', '#284FF_y@x', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (103, 'Dương Phạm', 'xpham@example.net', 'xS9#iV6h)1', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (104, 'Xuân Dương', 'john94@example.com', 'VEB9ORzi%4', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (105, 'Quang Vũ', 'jane50@example.net', '_4AbUXZbRJ', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (106, 'Tú Hoàng', 'john14@example.org', '*mW#N3QvEB', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (107, 'Bác Bảo Đặng', 'jane16@example.net', '(9oW6ZnoJi', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (108, 'Chị Linh Hoàng', 'jane78@example.net', '2x9gTHkm)n', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (109, 'Ông Vũ Bùi', 'john87@example.net', 'ID73JF*qS+', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (110, 'Lâm Mai', 'john43@example.org', '!!%2YNg*Wd', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (111, 'Khoa Phú Hoàng', 'phamjane@example.com', 'h+7z_EqO&m', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (112, 'Cô Hương Vũ', 'john54@example.com', 'QV2PumvB)_', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (113, 'Bà Lâm Vũ', 'john00@example.com', '^9NmSoDQcz', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (114, 'Chị Nhật Dương', 'bvu@example.org', '&p4lNnU!R+', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (115, 'Vân Đặng', 'john98@example.org', 'w5T)S6Nb^q', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (116, 'Chi Vũ', 'nguyenjohn@example.com', '_4*NnoBk_u', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (117, 'Hưng Trần', 'janehoang@example.net', 's*4KbV7a^e', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (118, 'An Thị Đặng', 'ghoang@example.org', '^eSOvxLpf9', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (119, 'Anh Trung Đặng', 'fle@example.net', '+lU(0OkJTP', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (120, 'Nhiên Mai', 'yle@example.org', '84Fvfz4B)4', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (121, 'Ông Quang Nguyễn', 'zdang@example.org', 'd_lJ)6AfP%', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (122, 'Ông Huy Trần', 'dangjohn@example.org', 'L)0V@BpeXb', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (123, 'Nhật Thị Trần', 'kvu@example.com', '%$1Q)Ueb9h', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (124, 'Quý ông Tú Phạm', 'janemai@example.com', '6uANwKiK+k', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (125, 'Hương Dương', 'johnnguyen@example.org', 'Sc)5ScpL+#', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (126, 'Kim Bảo Hoàng', 'john00@example.com', '9(7A5XOl^C', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (127, 'Châu Phú Phạm', 'maijohn@example.org', '#1f5r@Ik#l', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (128, 'Anh Bùi', 'jane62@example.net', 'q*h4@#Uj%7', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (129, 'Thảo Vũ', 'ddang@example.net', 'Y4ck4K7z%k', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (130, 'Bảo Phạm', 'jane31@example.net', '@0&7zNg98+', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (131, 'Chị Hạnh Trần', 'johntran@example.com', 'L$@A6OXeXb', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (132, 'Lâm Hải Phạm', 'lnguyen@example.net', '$3kaDLedDH', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (133, 'Phương Mai Hoàng', 'janetran@example.net', '@8OYHh*ei4', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (134, 'An Nguyễn', 'dangjohn@example.com', 'pyS+g5YyH&', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (135, 'Châu Thị Trần', 'maijohn@example.org', 'L#9ApC)759', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (136, 'Bảo Phạm', 'sduong@example.org', 'QW!1MsTvTK', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (137, 'Anh Lê', 'johnnguyen@example.net', '@9QDjZ6g#J', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (138, 'Quý cô An Dương', 'john34@example.org', '&^3Mmf*e&m', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (139, 'Hải Quang Trần', 'spham@example.com', 'Y19nlolh*L', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (140, 'Bác Khoa Bùi', 'vujane@example.com', '!TFYuWJ_3R', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (141, 'Quý cô Lâm Dương', 'jane28@example.net', '3%Rtja%Y+(', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (142, 'Phương Mai', 'john28@example.org', '@QYN1#Gt(T', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (143, 'Dương Vũ', 'jane25@example.com', '+0gp^JHx#g', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (144, 'Quý cô Kim Phạm', 'john43@example.org', '*J&dZ$nvA2', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (145, 'Hải Phạm', 'johnbui@example.net', 'o#5Z2Hb1X4', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (146, 'Trọng Lê', 'john80@example.net', '^3Q0^Fs@y%', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (147, 'An Dương', 'hoangjohn@example.com', ')3zSZ@ijpm', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (148, 'Quý cô Vân Hoàng', 'phamjohn@example.net', 'cmH#pQfr#4', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (149, 'An Thị Mai', 'john69@example.net', 'LKu4XrTnK$', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (150, 'Tú Đức Hoàng', 'jane10@example.net', 'PHv0R09y^&', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (151, 'Hà Lê', 'johnvu@example.org', '_3IyDlEfN0', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (152, 'Châu Dương', 'itran@example.net', '&)K!GCOt7C', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (153, 'Bác Dũng Lê', 'bbui@example.com', '_z3B*so*&)', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (154, 'Hoàng Bảo Trần', 'phamjohn@example.com', 'Ci7TNLu_(D', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (155, 'Quý cô Hạnh Phạm', 'john03@example.org', '$iaTRro&F6', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (156, 'Bác Hoàng Lê', 'qnguyen@example.org', '^51hLuBj_c', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (157, 'Bà Ngọc Đặng', 'dduong@example.org', 'ep58QtVu(^', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (158, 'Hoàng Lê', 'ybui@example.net', '&0T+uuwkbM', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (159, 'Hồng Phạm', 'jane39@example.com', '6uW9mplQ)D', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (160, 'Châu Trần', 'john71@example.com', '&IZ1Vir)JD', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (161, 'Quý cô Hạnh Bùi', 'nguyenjane@example.org', '#Zp58^Fu_&', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (162, 'Bảo Đức Đặng', 'zhoang@example.org', 'k6)dIlAi+2', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (163, 'Vân Dương', 'jane64@example.com', '93LQidn2@z', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (164, 'Nhật Lê', 'dangjane@example.net', 't5VdbY9^+D', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (165, 'Chị Thành Nguyễn', 'apham@example.org', '*71N&rDW#d', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (166, 'Cô Phương Lê', 'vujohn@example.org', '_i57V3qn#%', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (167, 'Trọng Phạm', 'john27@example.com', '&@H72I7lTh', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (168, 'Bác Anh Vũ', 'johnpham@example.net', 'CgFFbiu0$8', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (169, 'Quang Đặng', 'jane45@example.com', 'ZmZ0UDBg$u', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (170, 'Ông Dũng Nguyễn', 'janenguyen@example.com', 'u06GNjzD%1', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (171, 'Cô Thành Mai', 'janebui@example.com', 't8XC2*Cmk&', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (172, 'Châu Quang Trần', 'buijohn@example.com', 'T2q5M$mo_$', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (173, 'Kim Thế Lê', 'johnbui@example.net', '#7DG4Hp)Kp', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (174, 'Bảo Hoàng', 'janepham@example.org', 'y!9UZqQS_9', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (175, 'Kim Xuân Lê', 'ptran@example.net', 'K71ZtwSk*A', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (176, 'Thành Đặng', 'mpham@example.net', 'M48wSXx(__', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (177, 'Minh Trí Phạm', 'zduong@example.net', '8m8Q@Hzo5@', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (178, 'Châu Dương', 'jane18@example.org', '3BB6YywL$Q', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (179, 'Nhật Vũ', 'janele@example.org', 'K03GeYU1$q', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (180, 'Tú Nguyễn', 'janeduong@example.org', 'jRk_9I%zcd', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (181, 'Thành Hải Mai', 'jane48@example.org', '0jNx(*h1_w', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (182, 'Kim Dương', 'johnnguyen@example.net', '(6XjXt*Doz', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (183, 'Dũng Đức Vũ', 'maijohn@example.org', 'G^5OcLc5@7', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (184, 'Nhật Tấn Bùi', 'janevu@example.net', '^Obh)yKw3f', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (185, 'Cô Nhật Dương', 'jane63@example.net', 'icEGdNog_9', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (186, 'Quý cô Bảo Hoàng', 'ole@example.net', 'c3S4CsC!*2', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (187, 'Chi Dương', 'bpham@example.com', 'CEf&p0LnDN', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (188, 'Thành Quang Bùi', 'jane88@example.org', '%2dmZlmdFP', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (189, 'Thảo Nguyễn', 'duongjohn@example.net', 'mUnw0Hn3*l', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (190, 'Cô Mai Mai', 'nguyenjohn@example.com', 'in6Kh5eA@^', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (191, 'Khoa Trần', 'vujane@example.org', 'bKI_)cJJ*2', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (192, 'Quý cô Phương Nguyễn', 'qhoang@example.com', '^P0OmDkRH@', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (193, 'Thành Vũ', 'zbui@example.org', 'zRG*u7Hhwe', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (194, 'Thành Thị Phạm', 'vujohn@example.com', '*0@6rbVdAT', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (195, 'Bà Khoa Nguyễn', 'jane64@example.com', 'z#80mF6amq', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (196, 'Châu Nguyễn', 'johnle@example.com', '*6cGHtqjBN', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (197, 'Dương Vũ', 'john27@example.org', '@gw0FHkdDL', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (198, 'Châu Trần', 'lejohn@example.org', 'I4!SRiO7&1', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (199, 'Quý ông Hưng Đặng', 'janeduong@example.org', '9841Viho*j', 1);
INSERT INTO Users (Id, Name, Email, Password, IsActive) VALUES (200, 'Bảo Phạm', 'maijohn@example.org', '1W27IfAC*^', 1);